name: Test
on: [push]
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: wget -qO- https://deb.calamity.gg/key.gpg | sudo tee /usr/share/keyrings/calamity-inc.gpg > /dev/null
      - run: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/calamity-inc.gpg] https://deb.calamity.gg/ buster main" | sudo tee /etc/apt/sources.list.d/calamity-inc.list > /dev/null
      - run: sudo apt-get update
      - run: sudo apt-get install pluto
      - run: pluto test.pluto
      - run: plutoc -o evaluator.lua evaluator.pluto
      - run: plutoc -o test.lua test.pluto
      - uses: actions/upload-artifact@v3
        with:
          name: "Lua VM-compatible Bytecode"
          path: '*.lua'
